num_layers:  30
Traceback (most recent call last):
  File "evolve_neural_network.py", line 65, in <module>
    os.makedirs(data_dir_number_name)
  File "/usr/lib64/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: 'data/2019/201910/20191015/0005/'
num_layers:  30
Traceback (most recent call last):
  File "evolve_neural_network.py", line 65, in <module>
    os.makedirs(data_dir_number_name)
  File "/usr/lib64/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: 'data/2019/201910/20191015/0006/'
num_layers:  30
num_layers:  30
Traceback (most recent call last):
  File "evolve_neural_network.py", line 65, in <module>
    os.makedirs(data_dir_number_name)
  File "/usr/lib64/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: 'data/2019/201910/20191015/0011/'
Traceback (most recent call last):
  File "evolve_neural_network.py", line 65, in <module>
    os.makedirs(data_dir_number_name)
  File "/usr/lib64/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: 'data/2019/201910/20191015/0011/'
num_layers:  30
num_layers:  30
num_layers:  30
Traceback (most recent call last):
  File "evolve_neural_network.py", line 65, in <module>
    os.makedirs(data_dir_number_name)
  File "/usr/lib64/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: 'data/2019/201910/20191015/0012/'
Traceback (most recent call last):
  File "evolve_neural_network.py", line 65, in <module>
    os.makedirs(data_dir_number_name)
  File "/usr/lib64/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: 'data/2019/201910/20191015/0012/'
Traceback (most recent call last):
  File "evolve_neural_network.py", line 65, in <module>
    os.makedirs(data_dir_number_name)
  File "/usr/lib64/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: 'data/2019/201910/20191015/0012/'
srun: error: node003: task 7: Exited with exit code 1
srun: error: node002: task 3: Exited with exit code 1
srun: error: node004: tasks 8,11: Exited with exit code 1
srun: error: node005: tasks 12-14: Exited with exit code 1
num_layers:  30
population_size:  32
selection_size:  16
Setting up population.

MUTPB:  0.2
NGEN:  500
Traceback (most recent call last):
  File "evolve_neural_network.py", line 498, in <module>
    pop, fitnesses = main()
  File "evolve_neural_network.py", line 443, in main
    for g in range(1, NGEN):
TypeError: 'str' object cannot be interpreted as an integer
srun: error: node004: task 9: Exited with exit code 1
num_layers:  30
population_size:  32
selection_size:  16
Setting up population.

MUTPB:  0.2
NGEN:  500
Traceback (most recent call last):
  File "evolve_neural_network.py", line 498, in <module>
    pop, fitnesses = main()
  File "evolve_neural_network.py", line 443, in main
    for g in range(1, NGEN):
TypeError: 'str' object cannot be interpreted as an integer
srun: error: node003: task 5: Exited with exit code 1
num_layers:  30
population_size:  32
selection_size:  16
Setting up population.

MUTPB:  0.2
NGEN:  500
Traceback (most recent call last):
  File "evolve_neural_network.py", line 498, in <module>
    pop, fitnesses = main()
  File "evolve_neural_network.py", line 443, in main
    for g in range(1, NGEN):
TypeError: 'str' object cannot be interpreted as an integer
srun: error: node002: task 0: Exited with exit code 1
num_layers:  30
population_size:  32
selection_size:  16
Setting up population.

MUTPB:  0.2
NGEN:  500
Traceback (most recent call last):
  File "evolve_neural_network.py", line 498, in <module>
    pop, fitnesses = main()
  File "evolve_neural_network.py", line 443, in main
    for g in range(1, NGEN):
TypeError: 'str' object cannot be interpreted as an integer
srun: error: node003: task 6: Exited with exit code 1
num_layers:  30
population_size:  32
selection_size:  16
Setting up population.

MUTPB:  0.2
NGEN:  500
Traceback (most recent call last):
  File "evolve_neural_network.py", line 498, in <module>
    pop, fitnesses = main()
  File "evolve_neural_network.py", line 443, in main
    for g in range(1, NGEN):
TypeError: 'str' object cannot be interpreted as an integer
srun: error: node005: task 15: Exited with exit code 1
num_layers:  30
population_size:  32
selection_size:  16
Setting up population.

MUTPB:  0.2
NGEN:  500
Traceback (most recent call last):
  File "evolve_neural_network.py", line 498, in <module>
    pop, fitnesses = main()
  File "evolve_neural_network.py", line 443, in main
    for g in range(1, NGEN):
TypeError: 'str' object cannot be interpreted as an integer
srun: error: node004: task 10: Exited with exit code 1
num_layers:  30
population_size:  32
selection_size:  16
Setting up population.

MUTPB:  0.2
NGEN:  500
Traceback (most recent call last):
  File "evolve_neural_network.py", line 498, in <module>
    pop, fitnesses = main()
  File "evolve_neural_network.py", line 443, in main
    for g in range(1, NGEN):
TypeError: 'str' object cannot be interpreted as an integer
srun: error: node002: task 2: Exited with exit code 1
num_layers:  30
population_size:  32
selection_size:  16
Setting up population.

MUTPB:  0.2
NGEN:  500
Traceback (most recent call last):
  File "evolve_neural_network.py", line 498, in <module>
    pop, fitnesses = main()
  File "evolve_neural_network.py", line 443, in main
    for g in range(1, NGEN):
TypeError: 'str' object cannot be interpreted as an integer
srun: error: node002: task 1: Exited with exit code 1
num_layers:  30
population_size:  32
selection_size:  16
Setting up population.

MUTPB:  0.2
NGEN:  500
Traceback (most recent call last):
  File "evolve_neural_network.py", line 498, in <module>
    pop, fitnesses = main()
  File "evolve_neural_network.py", line 443, in main
    for g in range(1, NGEN):
TypeError: 'str' object cannot be interpreted as an integer
srun: error: node003: task 4: Exited with exit code 1
